name: Leaderboard Without Discord

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      path: 'main'
      ref: 'master'

    - uses: actions/checkout@v3
      path: '.state'
      ref: 'state'

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    - name: Build
      env:
        LEADER_URL: ${{ secrets.LEADER_URL }}
        SESSION_COOKIE: ${{ secrets.SESSION_COOKIE }}
      run: go run ./tools/leader

    - name: Persist State
      run: |
        cd .state
        git add . && git commit -m "state update" && git push -u origin state