# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Leaderboard

on:
  workflow_dispatch:
  schedule:
    # 9am (UTC = 3pm or 15 hundred o'clock)
    - cron: '0 15 * * *'
    # 9pm (UTC = 3am)
    - cron: '0 3 * * *'
    # testing ever 5 mins
    - cron: '*/5 * * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      env:
        LEADER_URL: ${{ secrets.LEADER_URL }}
        SESSION_COOKIE: ${{ secrets.SESSION_COOKIE }}
        DISCORD_URL: ${{ secrets.DISCORD_URL }}
      run: go run ./tools/leader
